server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: course-selection-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/course_selection_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.example.courseselection: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/course-selection.log

# JWT配置
jwt:
  secret: course-selection-system-secret-key-2024
  expiration: 86400000 # 24小时，单位毫秒
  refresh-expiration: 604800000 # 7天，单位毫秒

# 应用配置
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  upload:
    path: uploads/
    max-file-size: 10MB
    
  course-selection:
    default-max-credits: 30
    default-drop-days: 14

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.example.courseselection: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
      
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.example.courseselection: INFO
  file:
    name: /var/log/course-selection/application.log